Backtrace: fix unwanted semicolon
NO_BACKTRACE_MSG is ment to unwrap in function arguments parts
so it means that semicolon is not wanted.

error:
base/src/util/Backtrace.cpp:97:12: error: expected ')'
        write(fd, NO_BACKTRACE_MSG, sizeof(NO_BACKTRACE_MSG));

Fixes: 0043aa5 ("Backtrace: new class")

Signed-off-by: Peter Kubov <xkubov06@stud.fit.vutbr.cz>
Reviewed-by: Jan Viktorin <iviktorin@fit.vutbr.cz>