SerialPort: fix use of errno
errno is used but errno.h is not included.

error:
base/src/io/SerialPort.cpp:19:10: error: use of undeclared identifier 'errno'
        switch (errno) {

Fixes: 9246d6a ("SerialPort: new class")

Signed-off-by: Peter Kubov <xkubov06@stud.fit.vutbr.cz>
[changed errno.h to cerrno]
Reviewed-by: Jan Viktorin <iviktorin@fit.vutbr.cz>