FdStream: fix name of enum value
POLL_HUP is macro defined in signal.h.
In code is used as name for value in enum.

generated error:
base/src/io/FdStream.h:37:3: error: expected identifier
                POLL_HUP      = 0x08,

Fixes: 105f438 ("FdStream: new class")

Signed-off-by: Peter Kubov <xkubov06@stud.fit.vutbr.cz>
Reviewed-by: Jan Viktorin <iviktorin@fit.vutbr.cz>